project:
  type: website
  output-dir: _site

website:
  title: "Tidy R with OMOP workgroup"
  navbar:
    left:
      - text: Presentations
        menu:
          - text: "Index"
            href: Presentations/index.qmd
          - text: "All of Us"
            href: Presentations/allofus.qmd
          - text: "DrugUtilisation"
            href: Presentations/DrugUtilisation.qmd
  page-footer:
    left: "Â© 2025 Tidy R with OMOP Workgroup"
    right:
      - icon: github
        href: https://github.com/ohdsi/tidy-r-with-omop-wg

format:
  html:
    theme: cosmo
    toc: true
