on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

permissions:
  contents: write

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install R libraries in renv
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Download synthetic datasets
        run: |
          # create folder
          mkdir -p omock

          # export OMOP_DATA_FOLDER for subsequent steps
          echo "OMOP_DATA_FOLDER=$(pwd)/omock" >> $GITHUB_ENV

          # download GiBleed with omock from R
          Rscript -e "
            omock::downloadMockDataset('GiBleed')
            #omock::downloadMockDataset('synthea-covid19-200k')
            #omock::downloadMockDataset('synthea-covid19-10k')
          "

      - name: Render quarto website
        run: quarto render

      - name: Publish
        if: github.event_name != 'pull_request' # for PR the quarto will only be rendered when merged to main also published
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
          path: ./_site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
